# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TemposBotMenubar' do
  use_frameworks!

  # Pods for TemposBotMenubar
  pod 'FileKit', '~> 5.0.0'

  target 'TemposBotMenubarTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TemposBotMenubarUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
